export {
  getRecommendations,
  getRouteCandidatePlaces,
  getAlternatives,
  getPlaceById,
  moodCategories,
  referenceCards,
  goatPlacesDataset,
} from "./recommendationService";
export type { RecommendationRequestOptions } from "./recommendationService";
export {
  RECOMMENDATION_POLICY_VERSION,
  recommendGoatPlaces,
  getRecommendedPlaceIds,
} from "./goatRecommendationEngine";
export {
  ACCESSIBILITY_RECOMMENDATION_POINTS,
  evaluateCarAccessibility,
  evaluatePublicTransportAccessibility,
  getAccessibilityRecommendationScore,
} from "./accessibilityScoringPolicy";
export type {
  AccessibilityEvaluation,
  CarEvaluationInput,
  PublicTransportEvaluationInput,
} from "./accessibilityScoringPolicy";
export * from "./courseRecommendationTypes";
export type {
  Companion,
  DataStatus,
  LegacyRecommendationScoreBreakdown,
  MoodCategory,
  OriginType,
  Place,
  RecommendationCard,
  RecommendationResult,
  RecommendationRole,
  Transport,
  TravelOrigin,
  TravelPreferences,
  TravelPurpose,
  VisitTime,
} from "./types";
export type {
  GoatPlaceDataset,
  GoatPlace,
  GoatReferenceCardDataset,
  RecommendRequest,
  RecommendResult,
  RecommendationWarning,
  RecommendationDecisionAudit,
  RecommendationCard as GoatRecommendationCard,
  ScoreBreakdown as GoatScoreBreakdown,
} from "./goatRecommendationTypes";
export {
  COMPANION_OPTIONS,
  DISCOVERY_CATALOG_VERSION,
  MOOD_IDS,
  RECOMMENDATION_PURPOSE_OPTIONS,
  REFERENCE_CARD_IDS,
  TRANSPORT_OPTIONS,
  TRAVEL_PURPOSE_OPTIONS,
  VISIT_TIME_OPTIONS,
  discoverySelectionCatalog,
  getDiscoverySelection,
  isMoodId,
  isReferenceCardId,
  publicDiscoverySelections,
} from "./catalog";
export type {
  CatalogOption,
  CompanionValue,
  MoodId,
  RecommendationSelection,
  RecommendationSelectionInput,
  RecommendationPurposeValue,
  ReferenceCardId,
  TransportValue,
  TravelPurposeValue,
  VisitTimeValue,
} from "./catalog";
export {
  buildDiscoverySession,
  canonicalFeatureId,
  computeSelectionAvailability,
  DISCOVERY_POLICY_VERSION,
  DISCOVERY_RELATION_RULE_VERSION,
  derivePlaceRelation,
  getPhotoSearchHints,
  getReplacementCandidates,
  normalizePlaceFeatures,
  rankDiscoveryCandidates,
  replaceDiscoveryCard,
} from "./discoveryRecommendation";
export type {
  AllowedExpansion,
  CatalogSelection,
  DiscoveryCard,
  DiscoveryMode,
  DiscoveryPlace,
  DiscoveryRequest,
  DiscoverySession,
  DiscoveryTransportType,
  FeatureEvidence,
  FeatureState,
  MatchType,
  NormalizedCandidateConditions,
  NormalizedComparableCondition,
  NormalizedConditionsByPlaceId,
  PhotoSearchHints,
  PlaceRelation,
  RankedDiscoveryCandidate,
  ReplaceDiscoveryRequest,
  ReplaceDiscoveryResult,
  ReplaceReason,
  SceneFitBand,
  SelectionAvailability,
  SelectionDefinition,
  TodayFactor,
  TodaySkipReason,
  TodayStatus,
} from "./discoveryRecommendation";
