uploads = []
outputs = []

[[generated]]
id = "y8Dj0L5HxwWecsKP61aIl"
uri = "file://artifacts/goat-mobile/assets/images/icon.png"
type = "image"
title = "goat travel app icon"

[[generated]]
id = "nCH2rz6Fl-ppJbmaX62ic"
uri = "file://artifacts/goat-mobile/assets/images/hero-landing.png"
type = "image"
title = "goat landing hero"

[[generated]]
id = "fqDzdmHwSNe3pVlUd0YzQ"
uri = "file://artifacts/goat-mobile/assets/images/mood-alps.png"
type = "image"
title = "alps meadow mood"

[[generated]]
id = "53vzBqw7G1oB9ZlbUxTYX"
uri = "file://artifacts/goat-mobile/assets/images/mood-europe.png"
type = "image"
title = "europe garden mood"

[[generated]]
id = "QRls22-gCeHg5rcTI1pPa"
uri = "file://artifacts/goat-mobile/assets/images/mood-beach.png"
type = "image"
title = "beach surf mood"
