kind = "mobile"
previewPath = "/"
title = "GOAT - 강원도 감성 여행"
version = "1.0.0"
id = "artifacts/goat-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 24374

[services.development]
run = "pnpm --filter @workspace/goat-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/goat-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/goat-mobile", "run", "serve" ]

[services.env]
PORT = "24374"
BASE_PATH = "/"
