const colors = {
  light: {
    text: "#0F0F0F",
    tint: "#7C3AED",
    background: "#FFFFFF",
    foreground: "#0F0F0F",
    card: "#F8F5FF",
    cardForeground: "#0F0F0F",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#F3EEFF",
    secondaryForeground: "#5B21B6",
    muted: "#F3EEFF",
    mutedForeground: "#6B7280",
    accent: "#84CC16",
    accentForeground: "#1A2E05",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#EDE9FE",
    input: "#EDE9FE",
    // extras
    surface: "#F9F7FF",
    overlay: "rgba(124, 58, 237, 0.08)",
    roleBest: "#7C3AED",
    roleAlt: "#2563EB",
    roleWeather: "#059669",
    // Gangwon nature palette
    seaBlue: "#0284C7",
    seaBlueBg: "#F0F9FF",
    seaBlueBorder: "#BAE6FD",
    mountainGreen: "#15803D",
    mountainGreenBg: "#F0FDF4",
    mountainGreenBorder: "#BBF7D0",
    oliveGreen: "#4D7C0F",
    oliveGreenBg: "#F7FEE7",
    oliveGreenBorder: "#D9F99D",
    mistIndigo: "#4338CA",
    mistIndigoBg: "#EEF2FF",
    mistIndigoBorder: "#C7D2FE",
    sandBeige: "#92400E",
    sandBeigeBg: "#FEF3C7",
    sandBeigeBorder: "#FDE68A",
  },
  radius: 16,
};

export default colors;
