const colors = {
  light: {
    text: "#0F0F0F",
    tint: "#3A2374",
    background: "#FAFAF9",
    foreground: "#0F0F0F",
    card: "#F5F2FD",
    cardForeground: "#0F0F0F",
    primary: "#3A2374",
    primaryForeground: "#FFFFFF",
    secondary: "#EDEAF7",
    secondaryForeground: "#2D1A5E",
    muted: "#EDEAF7",
    mutedForeground: "#6B7280",
    accent: "#C6E33D",
    accentForeground: "#1A2E05",
    deepGreen: "#2E5D3D",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#DDD8F0",
    input: "#DDD8F0",
    // extras
    surface: "#F8F6FE",
    overlay: "rgba(58, 35, 116, 0.08)",
    roleBest: "#3A2374",
    roleAlt: "#2563EB",
    roleWeather: "#059669",
    // Gangwon nature palette
    seaBlue: "#0284C7",
    seaBlueBg: "#F0F9FF",
    seaBlueBorder: "#BAE6FD",
    mountainGreen: "#15803D",
    mountainGreenBg: "#F0FDF4",
    mountainGreenBorder: "#BBF7D0",
    oliveGreen: "#4D7C0F",
    oliveGreenBg: "#F7FEE7",
    oliveGreenBorder: "#D9F99D",
    mistIndigo: "#4338CA",
    mistIndigoBg: "#EEF2FF",
    mistIndigoBorder: "#C7D2FE",
    sandBeige: "#92400E",
    sandBeigeBg: "#FEF3C7",
    sandBeigeBorder: "#FDE68A",
  },
  radius: 16,
};

export default colors;
