import React, { useEffect, useRef, useState, type RefObject } from "react";
import { AccessibilityInfo, ActivityIndicator, findNodeHandle, InteractionManager, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import type { DiscoveryTransportType } from "@workspace/api-client-react";
import { BrandIcon } from "@/src/components/BrandIcon";
import { fonts, palette, radius, spacing } from "@/src/theme/editorial";

export type DiscoveryConditions = { transport: DiscoveryTransportType | undefined; today: boolean };
type Props = { visible: boolean; draft: DiscoveryConditions; loading?: boolean; disabled?: boolean; error?: string | null; returnFocusRef?: RefObject<View | null>; onChange: (next: DiscoveryConditions) => void; onApply: () => void; onClose: () => void };
const options: Array<{ value: DiscoveryTransportType | undefined; label: string }> = [{ value: undefined, label: "분위기 우선" }, { value: "CAR", label: "자차" }, { value: "PUBLIC_TRANSIT", label: "대중교통" }];

export function ConditionSheet({ visible, draft, loading = false, disabled = false, error, returnFocusRef, onChange, onApply, onClose }: Props) {
  const insets = useSafeAreaInsets();
  const closeRef = useRef<View>(null);
  const wasVisible = useRef(false);
  const closing = useRef(false);
  const [reduceMotion, setReduceMotion] = useState(false);
  useEffect(() => { void AccessibilityInfo.isReduceMotionEnabled().then(setReduceMotion); const subscription = AccessibilityInfo.addEventListener("reduceMotionChanged", setReduceMotion); return () => subscription.remove(); }, []);
  const focus = (target: View | null | undefined) => { if (Platform.OS === "web") { (target as unknown as { focus?: () => void } | null)?.focus?.(); return; } const handle = target ? findNodeHandle(target) : null; if (handle) AccessibilityInfo.setAccessibilityFocus(handle); };
  useEffect(() => { if (!visible && wasVisible.current) { wasVisible.current = false; const task = InteractionManager.runAfterInteractions(() => focus(returnFocusRef?.current)); return () => task.cancel(); } }, [returnFocusRef, visible]);
  const handleShow = () => { closing.current = false; wasVisible.current = true; focus(closeRef.current); };
  const handleClose = () => { if (closing.current) return; closing.current = true; onClose(); };
  return <Modal visible={visible} transparent animationType={reduceMotion ? "none" : "fade"} onRequestClose={handleClose} onShow={handleShow}><View style={styles.overlay}>
    <Pressable accessible={false} importantForAccessibility="no-hide-descendants" onPress={handleClose} style={StyleSheet.absoluteFill} />
    <View accessibilityViewIsModal style={[styles.sheet, { paddingBottom: Math.max(insets.bottom, spacing.sm) }]}><View style={styles.handle} /><View style={styles.header}><View style={styles.heading}><Text style={styles.title}>조건 조정</Text><Text style={styles.description}>적용하기 전까지 현재 세 곳은 바뀌지 않아요.</Text></View><Pressable ref={closeRef} accessibilityRole="button" accessibilityLabel="조건 조정 닫기" onPress={handleClose} style={styles.close}><BrandIcon name="close" size={20} color={palette.forest} /></Pressable></View>
      <ScrollView style={styles.body} contentContainerStyle={styles.bodyContent} showsVerticalScrollIndicator={false}><View style={styles.section}><Text style={styles.label}>이동 방법</Text><View accessibilityRole="radiogroup" style={styles.options}>{options.map((option) => <Pressable key={option.label} accessibilityRole="radio" accessibilityState={{ checked: draft.transport === option.value, disabled: loading || disabled }} disabled={loading || disabled} onPress={() => onChange({ ...draft, transport: option.value })} style={[styles.option, draft.transport === option.value && styles.optionActive]}><Text style={[styles.optionText, draft.transport === option.value && styles.optionTextActive]}>{option.label}</Text></Pressable>)}</View></View>
      <View style={styles.section}><Text style={styles.label}>오늘 조건</Text><Pressable accessibilityRole="checkbox" accessibilityState={{ checked: draft.today, disabled: loading || disabled }} disabled={loading || disabled} onPress={() => onChange({ ...draft, today: !draft.today })} style={[styles.today, draft.today && styles.todayActive]}><BrandIcon name="sunny-outline" size={19} color={palette.forest} /><View style={styles.todayCopy}><Text style={styles.todayTitle}>날씨와 방문 집중도 반영</Text><Text style={styles.todayDescription}>가능한 정보만 추천에 반영해요.</Text></View><BrandIcon name={draft.today ? "check" : "arrow-right"} size={18} color={palette.forest} /></Pressable></View>{error ? <Text accessibilityLiveRegion="polite" style={styles.error}>{error}</Text> : null}</ScrollView>
      <Pressable accessibilityRole="button" accessibilityLabel="조건 적용하기" accessibilityState={{ busy: loading, disabled: loading || disabled }} disabled={loading || disabled} onPress={onApply} style={[styles.apply, (loading || disabled) && styles.disabled]}>{loading ? <ActivityIndicator color={palette.white} /> : <Text style={styles.applyText}>조건 적용하기</Text>}</Pressable>
    </View>
  </View></Modal>;
}

const styles = StyleSheet.create({
  overlay: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(15, 48, 42, 0.52)" }, sheet: { maxHeight: "88%", borderTopLeftRadius: radius.lg, borderTopRightRadius: radius.lg, backgroundColor: palette.paper, paddingHorizontal: spacing.lg, paddingTop: spacing.sm }, handle: { alignSelf: "center", width: 42, height: 4, borderRadius: radius.pill, backgroundColor: palette.line }, header: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: spacing.md }, heading: { flex: 1 }, title: { fontFamily: fonts.serif, fontSize: 24, lineHeight: 32, color: palette.ink }, description: { marginTop: spacing.xxs, fontFamily: fonts.body, fontSize: 14, lineHeight: 21, color: palette.muted }, close: { minWidth: 48, minHeight: 48, alignItems: "center", justifyContent: "center", borderRadius: radius.pill, backgroundColor: palette.ivory }, body: { flexShrink: 1 }, bodyContent: { gap: spacing.lg, paddingVertical: spacing.lg }, section: { gap: spacing.sm }, label: { fontFamily: fonts.semibold, fontSize: 15, color: palette.ink }, options: { flexDirection: "row", flexWrap: "wrap", gap: spacing.xs }, option: { minHeight: 48, justifyContent: "center", borderRadius: radius.pill, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.paper, paddingHorizontal: spacing.md }, optionActive: { borderColor: palette.forest, backgroundColor: palette.forest }, optionText: { fontFamily: fonts.semibold, fontSize: 14, color: palette.forest }, optionTextActive: { color: palette.white }, today: { minHeight: 72, flexDirection: "row", alignItems: "center", gap: spacing.sm, borderRadius: radius.md, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.ivory, padding: spacing.sm }, todayActive: { borderColor: palette.forest, backgroundColor: palette.sage }, todayCopy: { flex: 1, gap: spacing.xxs }, todayTitle: { fontFamily: fonts.semibold, fontSize: 14, color: palette.forest }, todayDescription: { fontFamily: fonts.body, fontSize: 12, lineHeight: 18, color: palette.muted }, error: { fontFamily: fonts.medium, fontSize: 14, lineHeight: 21, color: palette.error }, apply: { minHeight: 54, alignItems: "center", justifyContent: "center", borderRadius: radius.pill, backgroundColor: palette.forest, marginBottom: spacing.sm }, applyText: { fontFamily: fonts.semibold, fontSize: 16, color: palette.white }, disabled: { opacity: 0.65 },
});
