import React from "react";
import { Linking, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { AppTabBar } from "@/src/components/AppTabBar";
import { BrandIcon } from "@/src/components/BrandIcon";
import { useApp } from "@/src/context/AppContext";
import { fonts, palette } from "@/src/theme/editorial";

export default function MapScreen() { const insets = useSafeAreaInsets(); const { course, recommendationSession } = useApp(); const cards = recommendationSession?.cards ?? []; return <View style={[styles.screen, { paddingTop: insets.top }]}><View style={styles.top}><Text style={styles.title}>여행 지도</Text></View><ScrollView contentContainerStyle={{ padding: 18, paddingBottom: 110 + insets.bottom }}>
  <View style={styles.map}><BrandIcon name="map" size={64} color={palette.forestSoft}/><Text style={styles.mapTitle}>{course?.courseTitle ?? "선택한 장소를 지도에서 확인하세요"}</Text><Text style={styles.mapText}>{course?.summary ?? "하루 코스를 만들면 이동 순서와 체류 시간이 여기에 표시돼요."}</Text></View>
  {(course?.stops ?? cards.map((card, i) => ({ order: i + 1, id: card.placeId, title: card.name, stayMinutes: 60, reason: card.reason }))).map((stop) => <View key={stop.id} style={styles.stop}><View style={styles.order}><Text style={styles.orderText}>{stop.order}</Text></View><View style={styles.stopCopy}><Text style={styles.stopTitle}>{stop.title}</Text><Text style={styles.stopMeta}>{stop.stayMinutes}분 체류 · {stop.reason}</Text></View><Pressable accessibilityLabel={`${stop.title} 카카오맵 열기`} onPress={() => Linking.openURL(`https://map.kakao.com/link/search/${encodeURIComponent(stop.title)}`)} style={styles.open}><BrandIcon name="external" size={18}/></Pressable></View>)}
  {course?.staticMap.fallbackMapSearchUrl && <Pressable onPress={() => Linking.openURL(course.staticMap.fallbackMapSearchUrl!)} style={styles.mapButton}><BrandIcon name="location" color={palette.white}/><Text style={styles.mapButtonText}>카카오맵에서 전체 보기</Text></Pressable>}
  </ScrollView><AppTabBar/></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: palette.ivory }, top: { height: 62, paddingHorizontal: 22, justifyContent: "center" }, title: { fontFamily: fonts.serif, fontSize: 25, color: palette.ink }, map: { minHeight: 220, borderRadius: 16, alignItems: "center", justifyContent: "center", padding: 25, backgroundColor: palette.sage }, mapTitle: { marginTop: 14, textAlign: "center", fontFamily: fonts.serif, fontSize: 19, color: palette.ink }, mapText: { marginTop: 8, textAlign: "center", fontFamily: fonts.body, fontSize: 13, lineHeight: 20, color: palette.muted }, stop: { minHeight: 76, flexDirection: "row", alignItems: "center", gap: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: palette.line }, order: { width: 34, height: 34, borderRadius: 17, alignItems: "center", justifyContent: "center", backgroundColor: palette.forest }, orderText: { fontFamily: fonts.bold, color: palette.white }, stopCopy: { flex: 1 }, stopTitle: { fontFamily: fonts.semibold, fontSize: 15, color: palette.ink }, stopMeta: { marginTop: 4, fontFamily: fonts.body, fontSize: 11, lineHeight: 16, color: palette.muted }, open: { width: 44, height: 44, alignItems: "center", justifyContent: "center" }, mapButton: { marginTop: 20, minHeight: 54, borderRadius: 27, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, backgroundColor: palette.forest }, mapButtonText: { fontFamily: fonts.semibold, color: palette.white } });
