import { useRouter } from "expo-router";
import React from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { AppTabBar } from "@/src/components/AppTabBar";
import { BrandIcon } from "@/src/components/BrandIcon";
import { GangwonSymbol } from "@/src/components/editorial/Brand";
import { useAuth } from "@/src/context/AuthContext";
import { fonts, palette } from "@/src/theme/editorial";

export default function ProfileScreen() { const router = useRouter(); const insets = useSafeAreaInsets(); const { session, signOut } = useAuth(); return <View style={[styles.screen, { paddingTop: insets.top }]}><View style={styles.top}><Text style={styles.title}>마이</Text></View><View style={styles.content}><View style={styles.avatar}><GangwonSymbol size={54}/></View><Text style={styles.name}>{session?.displayName ?? "여행자"}</Text><Text style={styles.email}>{session?.email ?? "GOAT와 강원의 장면을 찾아보세요"}</Text><View style={styles.info}><Info label="로그인 제공자" value={session?.provider === "kakao" ? "카카오" : session?.provider === "google" ? "Google" : "연결된 OAuth"}/><Info label="최근 로그인" value={session?.lastLoginAt ? new Date(session.lastLoginAt).toLocaleString("ko-KR") : "현재 세션"}/></View><Pressable onPress={async () => { await signOut(); router.replace("/"); }} style={styles.logout}><BrandIcon name="logout" color={palette.error}/><Text style={styles.logoutText}>로그아웃</Text></Pressable></View><AppTabBar/></View>; }
function Info({ label, value }: { label: string; value: string }) { return <View style={styles.infoRow}><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: palette.ivory }, top: { height: 62, paddingHorizontal: 22, justifyContent: "center" }, title: { fontFamily: fonts.serif, fontSize: 25, color: palette.ink }, content: { padding: 22, alignItems: "center" }, avatar: { width: 88, height: 88, borderRadius: 44, alignItems: "center", justifyContent: "center", backgroundColor: palette.sage }, name: { marginTop: 16, fontFamily: fonts.serif, fontSize: 22, color: palette.ink }, email: { marginTop: 5, fontFamily: fonts.body, fontSize: 13, color: palette.muted }, info: { width: "100%", marginTop: 30, borderRadius: 15, paddingHorizontal: 16, backgroundColor: palette.paper }, infoRow: { minHeight: 58, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: StyleSheet.hairlineWidth, borderColor: palette.line }, infoLabel: { fontFamily: fonts.medium, fontSize: 13, color: palette.muted }, infoValue: { fontFamily: fonts.semibold, fontSize: 13, color: palette.ink }, logout: { marginTop: 22, minHeight: 50, flexDirection: "row", alignItems: "center", gap: 8 }, logoutText: { fontFamily: fonts.semibold, color: palette.error } });
