import { useFocusEffect, useRouter } from "expo-router";
import React, { useCallback, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { deleteRecommendation, getRecentRecommendations, type RecommendationData } from "@workspace/api-client-react";
import { AppTabBar } from "@/src/components/AppTabBar";
import { BrandIcon, type BrandIconName } from "@/src/components/BrandIcon";
import { useApp } from "@/src/context/AppContext";
import { buildRecommendationAttempt, hydrateRecommendationSession, selectionFromRequest } from "@/src/services/recommendationApi";
import { fonts, palette, radius } from "@/src/theme/editorial";

export default function RecommendationsScreen() {
  const router = useRouter(); const insets = useSafeAreaInsets(); const { setRecommendationSession, setPendingAttempt } = useApp(); const [items, setItems] = useState<RecommendationData[]>([]); const [loading, setLoading] = useState(true);
  const load = useCallback(() => { setLoading(true); getRecentRecommendations({ limit: 20 }).then((r) => setItems(r.data.items)).catch(() => setItems([])).finally(() => setLoading(false)); }, []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const remove = (item: RecommendationData) => Alert.alert("추천 기록을 지울까요?", "삭제한 기록은 복구할 수 없어요.", [{ text: "취소", style: "cancel" }, { text: "삭제", style: "destructive", onPress: async () => { await deleteRecommendation(item.recommendationId); setItems((prev) => prev.filter((x) => x.recommendationId !== item.recommendationId)); } }]);
  const reopen = (item: RecommendationData) => { setRecommendationSession(hydrateRecommendationSession(item)); router.push("/results"); };
  const rerun = (item: RecommendationData) => { setPendingAttempt(buildRecommendationAttempt({ selection: selectionFromRequest(item.conditions), preferences: item.conditions.preferences, origin: item.conditions.origin, rerollOfRecommendationId: item.recommendationId, excludeIds: item.cards.map((c) => c.placeId) })); router.push("/analyzing"); };
  return <View style={[styles.screen, { paddingTop: insets.top }]}><View style={styles.top}><Text style={styles.eyebrow}>여행 기록</Text><Text style={styles.topTitle}>최근 추천</Text><Text style={styles.topCopy}>마음에 남은 여행의 단서를 다시 꺼내보세요.</Text></View>
    <ScrollView contentContainerStyle={{ paddingHorizontal: 16, paddingBottom: 110 + insets.bottom }} showsVerticalScrollIndicator={false}>
      {loading ? <Empty icon="time" title="추천 기록을 불러오는 중이에요" /> : items.length === 0 ? <Empty icon="recommend" title="아직 추천 기록이 없어요" body="감성을 고르고 첫 강원 여행을 추천받아 보세요." action={() => router.push("/mood-selection")} /> : <View style={styles.list}>{items.map((item, index) => <Pressable key={item.recommendationId} accessibilityLabel={`${formatDate(item.createdAt)} 추천 결과 보기`} onPress={() => reopen(item)} style={styles.card}><View style={styles.cardHead}><View><Text style={styles.index}>{String(index + 1).padStart(2, "0")}</Text><Text style={styles.date}>{formatDate(item.createdAt)}</Text></View><Pressable accessibilityLabel="추천 기록 삭제" onPress={(e) => { e.stopPropagation(); remove(item); }} style={styles.delete}><BrandIcon name="delete" size={18} color={palette.muted} /></Pressable></View><Text style={styles.cardTitle} numberOfLines={2}>{item.cards.map((c) => c.name).join(" · ")}</Text><Text style={styles.summary} numberOfLines={2}>{item.originNotice ?? "고른 분위기와 이동 방식에 맞춘 여행지"}</Text><View style={styles.divider} /><View style={styles.cardBottom}><Pressable accessibilityLabel="같은 조건으로 다시 추천" onPress={(e) => { e.stopPropagation(); rerun(item); }} style={styles.rerun}><Text style={styles.rerunText}>다시 추천</Text><BrandIcon name="refresh" size={15} color={palette.forest} /></Pressable></View></Pressable>)}</View>}
    </ScrollView><AppTabBar /></View>;
}
function Empty({ icon, title, body, action }: { icon: BrandIconName; title: string; body?: string; action?: () => void }) { return <View style={styles.empty}><View style={styles.emptyIcon}><BrandIcon name={icon} size={32} color={palette.forest} /></View><Text style={styles.emptyTitle}>{title}</Text>{body && <Text style={styles.emptyBody}>{body}</Text>}{action && <Pressable onPress={action} style={styles.emptyAction}><Text style={styles.emptyActionText}>추천 시작하기</Text></Pressable>}</View>; }
function formatDate(value: string) { return new Intl.DateTimeFormat("ko-KR", { month: "long", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value)); }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: palette.ivory }, top: { paddingHorizontal: 22, paddingTop: 17, paddingBottom: 27 }, eyebrow: { fontFamily: fonts.bold, fontSize: 9, letterSpacing: 1.7, color: palette.forestSoft }, topTitle: { marginTop: 7, fontFamily: fonts.serif, fontSize: 30, color: palette.ink }, topCopy: { marginTop: 8, fontFamily: fonts.body, fontSize: 14, lineHeight: 21, color: palette.muted }, list: { gap: 14 }, card: { padding: 18, borderRadius: radius.lg, backgroundColor: palette.paper, borderWidth: StyleSheet.hairlineWidth, borderColor: palette.line }, cardHead: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between" }, index: { fontFamily: fonts.serifRegular, fontSize: 26, lineHeight: 28, color: palette.forest }, date: { marginTop: 4, fontFamily: fonts.medium, fontSize: 11, color: palette.muted }, delete: { width: 42, height: 42, alignItems: "center", justifyContent: "center" }, cardTitle: { marginTop: 18, fontFamily: fonts.serif, fontSize: 20, lineHeight: 29, color: palette.ink }, summary: { marginTop: 7, fontFamily: fonts.body, fontSize: 13, lineHeight: 20, color: palette.muted }, divider: { height: StyleSheet.hairlineWidth, backgroundColor: palette.line, marginTop: 16 }, cardBottom: { marginTop: 11, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, version: { fontFamily: fonts.medium, fontSize: 9, color: palette.sageDark }, rerun: { minHeight: 38, flexDirection: "row", alignItems: "center", gap: 5 }, rerunText: { fontFamily: fonts.semibold, fontSize: 12, color: palette.forest }, empty: { paddingTop: 106, alignItems: "center", paddingHorizontal: 24 }, emptyIcon: { width: 70, height: 70, borderRadius: 35, alignItems: "center", justifyContent: "center", backgroundColor: palette.sage }, emptyTitle: { marginTop: 18, fontFamily: fonts.serif, fontSize: 21, color: palette.ink }, emptyBody: { marginTop: 8, textAlign: "center", fontFamily: fonts.body, fontSize: 14, lineHeight: 22, color: palette.muted }, emptyAction: { marginTop: 22, minHeight: 48, paddingHorizontal: 22, borderRadius: 24, justifyContent: "center", backgroundColor: palette.forest }, emptyActionText: { fontFamily: fonts.semibold, color: palette.white } });
