import { useFocusEffect, useRouter } from "expo-router";
import React, { useCallback, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { deleteRecommendation, getRecentRecommendations, type RecommendationData } from "@workspace/api-client-react";
import { AppTabBar } from "@/src/components/AppTabBar";
import { BrandIcon, type BrandIconName } from "@/src/components/BrandIcon";
import { useApp } from "@/src/context/AppContext";
import { buildRecommendationAttempt, hydrateRecommendationSession, selectionFromRequest } from "@/src/services/recommendationApi";
import { fonts, palette } from "@/src/theme/editorial";

export default function RecommendationsScreen() {
  const router = useRouter(); const insets = useSafeAreaInsets(); const { setRecommendationSession, setPendingAttempt } = useApp(); const [items, setItems] = useState<RecommendationData[]>([]); const [loading, setLoading] = useState(true);
  const load = useCallback(() => { setLoading(true); getRecentRecommendations({ limit: 20 }).then((r) => setItems(r.data.items)).catch(() => setItems([])).finally(() => setLoading(false)); }, []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const remove = (item: RecommendationData) => Alert.alert("추천 기록을 삭제할까요?", "삭제한 기록은 복구할 수 없어요.", [{ text: "취소", style: "cancel" }, { text: "삭제", style: "destructive", onPress: async () => { await deleteRecommendation(item.recommendationId); setItems((prev) => prev.filter((x) => x.recommendationId !== item.recommendationId)); } }]);
  return <View style={[styles.screen, { paddingTop: insets.top }]}><Top title="최근 추천"/>
    <ScrollView contentContainerStyle={{ padding: 18, paddingBottom: 110 + insets.bottom }}>
      {loading ? <Empty icon="time" title="추천 기록을 불러오고 있어요"/> : items.length === 0 ? <Empty icon="recommend" title="아직 추천 기록이 없어요" body="감성을 골라 첫 강원 여행을 추천받아보세요." action={() => router.push("/mood-selection")}/> : items.map((item) => <Pressable key={item.recommendationId} onPress={() => { setRecommendationSession(hydrateRecommendationSession(item)); router.push("/results"); }} style={styles.card}><View style={styles.cardTop}><Text style={styles.date}>{formatDate(item.createdAt)}</Text><Pressable accessibilityLabel="추천 기록 삭제" onPress={(e) => { e.stopPropagation(); remove(item); }} style={styles.iconButton}><BrandIcon name="delete" size={19}/></Pressable></View><Text style={styles.cardTitle}>{item.cards.map((c) => c.name).join(" · ")}</Text><Text style={styles.summary}>{item.originNotice ?? "감성과 이동 조건으로 고른 세 곳"}</Text><View style={styles.cardBottom}><Text style={styles.version}>{item.policyVersion}</Text><Pressable onPress={(e) => { e.stopPropagation(); setPendingAttempt(buildRecommendationAttempt({ selection: selectionFromRequest(item.conditions), preferences: item.conditions.preferences, origin: item.conditions.origin, rerollOfRecommendationId: item.recommendationId, excludeIds: item.cards.map((c) => c.placeId) })); router.push("/analyzing"); }} style={styles.rerun}><BrandIcon name="refresh" size={16}/><Text style={styles.rerunText}>같은 조건으로 다시 추천</Text></Pressable></View></Pressable>)}
    </ScrollView><AppTabBar/></View>;
}
function Top({ title }: { title: string }) { return <View style={styles.top}><Text style={styles.topTitle}>{title}</Text></View>; }
function Empty({ icon, title, body, action }: { icon: BrandIconName; title: string; body?: string; action?: () => void }) { return <View style={styles.empty}><BrandIcon name={icon} size={48} color={palette.forestSoft}/><Text style={styles.emptyTitle}>{title}</Text>{body && <Text style={styles.emptyBody}>{body}</Text>}{action && <Pressable onPress={action} style={styles.emptyAction}><Text style={styles.emptyActionText}>추천 시작하기</Text></Pressable>}</View>; }
function formatDate(value: string) { return new Intl.DateTimeFormat("ko-KR", { month: "long", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value)); }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: palette.ivory }, top: { height: 62, paddingHorizontal: 22, justifyContent: "center" }, topTitle: { fontFamily: fonts.serif, fontSize: 25, color: palette.ink }, card: { marginBottom: 12, padding: 17, borderRadius: 15, backgroundColor: palette.paper }, cardTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, date: { fontFamily: fonts.medium, fontSize: 11, color: palette.muted }, iconButton: { width: 44, height: 44, alignItems: "center", justifyContent: "center" }, cardTitle: { fontFamily: fonts.serif, fontSize: 18, lineHeight: 28, color: palette.ink }, summary: { marginTop: 6, fontFamily: fonts.body, fontSize: 13, lineHeight: 20, color: palette.muted }, cardBottom: { marginTop: 14, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, version: { fontFamily: fonts.medium, fontSize: 9, color: palette.sageDark }, rerun: { minHeight: 44, flexDirection: "row", alignItems: "center", gap: 5 }, rerunText: { fontFamily: fonts.semibold, fontSize: 11, color: palette.forest }, empty: { paddingTop: 120, alignItems: "center" }, emptyTitle: { marginTop: 18, fontFamily: fonts.serif, fontSize: 20, color: palette.ink }, emptyBody: { marginTop: 8, textAlign: "center", fontFamily: fonts.body, fontSize: 14, lineHeight: 22, color: palette.muted }, emptyAction: { marginTop: 20, minHeight: 48, paddingHorizontal: 22, borderRadius: 24, justifyContent: "center", backgroundColor: palette.forest }, emptyActionText: { fontFamily: fonts.semibold, color: palette.white } });
