import { useFocusEffect, useRouter } from "expo-router";
import React, { useCallback, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { deleteBookmark, getBookmarks } from "@workspace/api-client-react";
import { AppTabBar } from "@/src/components/AppTabBar";
import { BrandIcon } from "@/src/components/BrandIcon";
import { fonts, palette } from "@/src/theme/editorial";

type BookmarkItem = { placeId?: string; place_id?: string; placeName?: string; place_name_at_save?: string; region?: string; region_at_save?: string };
export default function SavedScreen() { const router = useRouter(); const insets = useSafeAreaInsets(); const [items, setItems] = useState<BookmarkItem[]>([]); const load = useCallback(() => { getBookmarks().then((r) => setItems(r.data.items as BookmarkItem[])).catch(() => setItems([])); }, []); useFocusEffect(useCallback(() => { load(); }, [load])); return <View style={[styles.screen, { paddingTop: insets.top }]}><View style={styles.top}><Text style={styles.title}>저장한 곳</Text></View><ScrollView contentContainerStyle={{ padding: 18, paddingBottom: 110 + insets.bottom }}>{items.length === 0 ? <View style={styles.empty}><BrandIcon name="bookmark" size={50} color={palette.forestSoft}/><Text style={styles.emptyTitle}>저장한 장소가 없어요</Text><Text style={styles.emptyText}>추천 결과에서 마음에 드는 장소를 저장해보세요.</Text></View> : items.map((item) => { const id = item.placeId ?? item.place_id ?? ""; const name = item.placeName ?? item.place_name_at_save ?? id; const region = item.region ?? item.region_at_save ?? "강원"; return <Pressable key={id} onPress={() => router.push(`/detail/${id}` as never)} style={styles.row}><View style={styles.mark}><BrandIcon name="location"/></View><View style={styles.copy}><Text style={styles.name}>{name}</Text><Text style={styles.region}>{region}</Text></View><Pressable accessibilityLabel="저장 해제" onPress={async (e) => { e.stopPropagation(); await deleteBookmark(id); setItems((prev) => prev.filter((x) => (x.placeId ?? x.place_id) !== id)); }} style={styles.remove}><BrandIcon name="bookmark" filled/></Pressable></Pressable>; })}</ScrollView><AppTabBar/></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: palette.ivory }, top: { height: 62, paddingHorizontal: 22, justifyContent: "center" }, title: { fontFamily: fonts.serif, fontSize: 25, color: palette.ink }, row: { minHeight: 82, flexDirection: "row", alignItems: "center", gap: 13, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: palette.line }, mark: { width: 48, height: 48, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: palette.sage }, copy: { flex: 1 }, name: { fontFamily: fonts.serif, fontSize: 16, color: palette.ink }, region: { marginTop: 4, fontFamily: fonts.body, fontSize: 12, color: palette.muted }, remove: { width: 48, height: 48, alignItems: "center", justifyContent: "center" }, empty: { paddingTop: 130, alignItems: "center" }, emptyTitle: { marginTop: 18, fontFamily: fonts.serif, fontSize: 20, color: palette.ink }, emptyText: { marginTop: 8, fontFamily: fonts.body, fontSize: 14, color: palette.muted } });
